### ISSUE TITLE
Rename the code repository

### ISSUE THREAD

**Issue by maphew** [lazarus-recovery/lazarus_addon#10]
`original_ff` isn't a very good name for this repository. We should change it to something more descriptive and natural.  I'm thinking just plain ol' `lazarus`. Any other suggestions?

According to the Github docs the change will be almost completely transparent to anyone using the old name: https://help.github.com/articles/renaming-a-repository/

**Comment by maphew** [comment]
`lazarus-resurrected` for wonderful recursion and punning

**Comment by BubiBalboa** [comment]
I feel like dropping Lazarus name might be the better choice but I'm not sure. What are the pros and cons of keeping it?
+ recognizable for former users
+ cool name
- meaningless for new users (what does it do?)
- may create confusion on who is behind the addon

**Comment by sierracircle** [comment]
The original_ff was not meant to be the repository for our new WebExtension add-on, but rather the old xpi.
I think we should open a new repository for the updated WebExtension version and keep the xpi version (original_ff) in place for historical reference.

**Comment by sierracircle** [comment]
The new name should probably include firefox (or ff) since we plan on also updating/migrating a Chrome version as well.
lazarus_ff  and lazarus_chrome or something like it

**Comment by maphew** [comment]
We don't need a separate repo for the historical version. I'll create a tag and a release from when it was imported (without changes). People needing to refer back to original can use the tag and/or release.

**Comment by maphew** [comment]
Original binaries and their associated branches in the repository are posted in this release:
https://github.com/lazarus-recovery/lazarus_addon/releases/tag/v3.2.0_original

Renamed repo from `original_ff` to `lazarus_addon`. The github docs say all clients and bookmarks will be seamlessly redirected to the new name.
