### ISSUE TITLE
Utils should be in its own repository

### ISSUE THREAD

**Issue by sierracircle** [lazarus-recovery/lazarus_addon#16]
The main repository should only have files for the actual add-on, and not extra utilities. It should also not be in a sub-folder. It is okay to have a Utilities repository if you think it is necessary, but please do not add it in to the main repository.

**Comment by maphew** [comment]
There's a theme here and in #10 about separate repo's per browser I'd like to explore and understand. 

In my thinking each of these are part of the same project. The Chrome extension if/when it materializes will share resources with the Firefox one, and bugs & enhancement in one are likely to be in the other as well. It will be easier to see and manage these shared bits if they are close to each other. The utilities are similarly integral. 

Thinking about what you've said, you would like to have one single container that is just "lazarus_firefox" extension and nothing else. Wrap that puppy up in an xpi and you have an extension there and then. Repeat for "lazarus_chrome" and anything else that comes up. 

What I've named `src` is that "lazarus_firefox" container, it is the extension and nothing else. Would renaming `src` to `firefox` solve your itch or is there more I'm missing?

`lazarus_repo\firefox`
`lazarus_repo\chrome`
`lazarus_repo\utils`

At the end of the day my intention over the long haul is to be a supportive but somewhat background player. As such I'm happy adjust my work habits and view to match yours. Doing that is easier if I understand why you would choose structure X over structure Y.

**Comment by sierracircle** [comment]
Now that you mention it, I remember that once Lazarus is further developed it should also work in Chrome without modifications.  I was thinking it was going to be a different creature all-together, but it should not have to be separate, like you say.

With that in mind, what I would like is three separate repositories, which can be named whatever, but for example:   lazarus, original_ff, and utils.

The reason for an original repository is that Palemoon Browser still supports older FF extensions, and even has their own web-store. I was going to submit the previous lazarus to the Palemoon store and do occassional updates on it (for example, if we re-do the icons).

The reason for having a separate repository for utils is that those of us working on Macs or Linux boxes do not need any of that. 
When I am working on a thing, I pull directly into a folder and work from there and submit changes from there. Having extra folders that are not needed is redundant, as is putting the code into uneeded sub-folders.

You are welcome to have a separate repository here for that, and update it as needed, but I feel like it is cruft for those of us not needing it and adds extra steps to a clean workflow.

**Comment by sierracircle** [comment]
@maphew 
I discussed this issue with my developer friends and they suggested leaving the utils folder in place, but just having it as a subdirectory rather than having a src folder.

That way I can just do a git -ignore for the utils folder.

**Comment by maphew** [comment]
Ok, I read up on `gitignore`. I didn't know personal ones were possible, but they are: https://stackoverflow.com/questions/5724455/can-i-make-a-user-specific-gitignore-file. That's good to know. However having an extra step of adding that file and then populating it adds friction and doesn't align with a clean workflow. I'll back off lumping together and adapt.

So how about these 3 repo names?

```
lazarus_webext
lazarus_original
lazarus_utils
```

**Comment by sierracircle** [comment]
What my developer friends were getting at is that it is more important to have people involved and feeling included than it is to have a clean workflow. I can see what they are saying.

I am no longer against having a utils folder, but I do feel that the files you currently have in src should be in the top-level of the repository and utils as a subdirectory, rather than having a src folder.

**Comment by maphew** [comment]
Hey Adam. I haven't been ignoring, just too busy to think about it!

My main motivation for a subfolder (though I now I think `./addon` would be better than `src`) is so that there's no wondering what's actually needed for distribution and what's just scaffolding to help during development and building; Just bundle everything in `addon` and go. So I think we're both after the same thing, just using different container types. I'll follow your preference in this one and create repos:

```
./lazarus_addon
./lazarus_utils
```

**Comment by maphew** [comment]
new utils repo created, but I've run out of time to move things over today.
https://github.com/lazarus-recovery/lazarus_utils

**Comment by maphew** [comment]
ok done

**Comment by sierracircle** [comment]
Thanks Matt. Everything is looking great. I wont be able to work on it this tomorrow, but will start next  this weekend on testing your recent updates to make sure things are working.
