### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by Hueristic** [lazarus-recovery/lazarus_addon#18]
I have  used this extension for years on Bitcointalk.org but it no longer works and I tried it on another site as well and it failed so is there a test site I can try this on? I am not sure what has changed as I do not update FF.

**Comment by guysoft** [comment]
Its working for me on firefox 59

**Comment by Hueristic** [comment]
Thanks for commenting it reminded me of this, I re-enabled it a week ago and it started working again so I'm inclined to believe it was a browser issue that interfered with the plugin as I had a lot of browser related issues after this post. Closing :)
